<?php
namespace common\components;

use Yii;
use yii\base\Object;

/**
 * @desc  基础 model ,先留着，万一用得着呢
 * Class BaseModel
 * @package common\components
 */
class BaseModel extends Object
{
    protected $_model = null;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

}