<?php

namespace common\components;

use Yii;
use yii\web\View;
use yii\base\ViewContextInterface;
use yii\base\InvalidCallException;


/**
 * Class BaseView
 * @package common\components
 * @desc 重写视图类，findViewFile的重写是为了重找模板，现已在config/common/main.php配置【components/view】
 * 先留着，万一用得着呢
 */
class BaseView extends View
{

    /**
     * @var \common\controllers\BaseController
     */
    public $context;

//    public function init()
//    {
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    /**
     * Finds the view file based on the given view name.
     * @param string $view the view name or the path alias of the view file. Please refer to [[render()]]
     * on how to specify this parameter.
     * @param object $context the context to be assigned to the view and can later be accessed via [[context]]
     * in the view. If the context implements [[ViewContextInterface]], it may also be used to locate
     * the view file corresponding to a relative view name.
     * @return string the view file path. Note that the file may not exist.
     * @throws InvalidCallException if a relative view name is given while there is no active context to
     * determine the corresponding view file.
     *
     * protected function findViewFile($view, $context = null)
     * {
     * if (strncmp($view, '@', 1) === 0) {
     * // e.g. "@app/views/main"
     * $file = Yii::getAlias($view);
     * } elseif (strncmp($view, '//', 2) === 0) {
     * // e.g. "//layouts/main"
     * $file = Yii::$app->getViewPath() . DIRECTORY_SEPARATOR . ltrim($view, '/');
     * } elseif (strncmp($view, '/', 1) === 0) {
     * // e.g. "/site/index"
     * if (Yii::$app->controller !== null) {
     * $file = Yii::$app->controller->module->getViewPath() . DIRECTORY_SEPARATOR . ltrim($view, '/');
     * } else {
     * throw new InvalidCallException("Unable to locate view file for view '$view': no active controller.");
     * }
     * } elseif ($context instanceof ViewContextInterface) {
     * $file = $context->getViewPath() . DIRECTORY_SEPARATOR . $view;
     * } elseif (($currentViewFile = $this->getViewFile()) !== false)
     * {
     * $file = dirname($currentViewFile) . DIRECTORY_SEPARATOR . $view;
     *
     * //规则重写
     * if (pathinfo($file, PATHINFO_EXTENSION) == '')
     * {//如果视图没有后缀
     * $file = $file . '.' . $this->defaultExtension;
     * if ($this->defaultExtension !== 'php' && !is_file($file))
     * {
     * $file = $file . '.php';
     * }
     * }
     * if(!is_file($file))
     * {//视图文件不存在
     * if (stripos($file,'layouts')){
     * $file = '@common/views/'.SITE_TYPE.'/layouts'.DIRECTORY_SEPARATOR . $view;
     * }else{
     *
     * $file = '@common/views/'.SITE_TYPE.'/' . Yii::$app->controller->id . DIRECTORY_SEPARATOR . $view;
     * }
     * }
     * } else {
     * throw new InvalidCallException("Unable to resolve view file for view '$view': no active view context.");
     * }
     *
     * if (pathinfo($file, PATHINFO_EXTENSION) !== '') {
     * return $file;
     * }
     * $path = $file . '.' . $this->defaultExtension;
     * if ($this->defaultExtension !== 'php' && !is_file($path)) {
     * $path = $file . '.php';
     * }
     *
     * return $path;
     * }
     */

}